config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, controllers: {
  sessions:      'admins/sessions',
  passwords:     'admins/passwords',
  # registrations: 'admins/registrations'
}

  devise_for :users, controllers: {
  sessions:      'users/sessions',
  passwords:     'users/passwords',
  registrations: 'users/registrations'
}

  scope module: :users do
    root 'home#top'
    get 'about' => 'home#about', as: :about
    get 'level' => 'questions#level', as: :level
    resources :users, only: [:show, :edit, :update]
    resources :words, only: [:index] do
      resource :favorites, only: [:create, :destroy]
    end
    resources :favorites, only: [:index]
    resources :questions, only: [:show, :create]
    post 'questions/:id' => 'questions#next', as: :next
    resources :results, only: [:index, :show]
  end

  get 'search' => 'search#search', as: :search

  namespace :admins do
    resources :admins, only: [:show, :edit, :update]
    resources :genres, only: [:index, :create, :edit, :update]
    resources :words, only: [:index, :new, :show, :create, :edit, :update]
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/choice.rb
class Choice < ApplicationRecord
  belongs_to :word
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :word
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :words

  validates :name, presence: true, length: {maximum: 50}
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :user
  belongs_to :word
end

app/models/result.rb
class Result < ApplicationRecord
  belongs_to :user
  has_many :result_details, dependent: :destroy
end

app/models/result_detail.rb
class ResultDetail < ApplicationRecord
  belongs_to :word
  belongs_to :result
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :authentication_keys => [:name]

  has_many :questions, dependent: :destroy
  has_many :results, dependent: :destroy
  has_many :favorites, dependent: :destroy

  # バリデーション
  validates :name, presence: true, uniqueness: true, length: {maximum: 50}

  #登録時にメールアドレスを不要とする
  def email_required?
    false
  end

  def email_changed?
    false
  end
end

app/models/word.rb
class Word < ApplicationRecord
	# refile指定のカラムにアクセス
	attachment :image

	belongs_to :genre

	has_many :favorites, dependent: :destroy
	has_many :questions, dependent: :destroy
	has_many :result_details, dependent: :destroy
	has_many :choices, dependent: :destroy

	accepts_nested_attributes_for :choices

	validates :english, presence: true, length: {maximum: 50}
	validates :japanese, presence: true, length: {maximum: 50}

	def favorite_by?(user)
		favorites.where(user_id: user.id).exists?
	end
end

app/controllers/admins/genres_controller.rb
class Admins::GenresController < ApplicationController
  before_action :authenticate_admin!

  def index
    @genres = Genre.all
    @genre = Genre.new
  end

  def create
    @genre = Genre.new(genre_params)
    if @genre.save
      redirect_to admins_genres_path
    else
      @genres = Genre.all
      render :index
    end
  end

  def edit
    @genre = Genre.find(params[:id])
  end

  def update
    @genre = Genre.find(params[:id])
    if @genre.update(genre_params)
      redirect_to admins_genres_path
    else
      render :edit
    end
  end

  private

    def genre_params
      params.require(:genre).permit(:name, :is_valid)
    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  protected

  def after_sign_in_path_for(resource_or_scope)
    if resource_or_scope.is_a?(Admin)
      admins_admin_path(current_admin)
    else
      level_path
    end
  end

  #sign_out後のredirect先変更する。
  def after_sign_out_path_for(resource_or_scope)
    if resource_or_scope == :user
      root_path
    elsif resource_or_scope == :admin
      new_admin_session_path
    else
      root_path
    end
  end

  Refile.secret_key = '9965eb0ced03aae4584924c8af339f5521d5bd5a8e7e68f158b12b57ea6a0dc8f2cd99f49dd9f4140b4005b4345e57f1da38d037b9c045d40ef3b61179d8418b'
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  def search
    @text = params[:search][:text]
    @words = Word.where(['english LIKE ? OR japanese LIKE ?', '%'+@text+'%', '%'+@text+'%'])
  end
end

app/helpers/admins/admins_helper.rb
module Admins::AdminsHelper
end

app/helpers/admins/genres_helper.rb
module Admins::GenresHelper
end

app/helpers/admins/home_helper.rb
module Admins::HomeHelper
end

app/helpers/admins/words_helper.rb
module Admins::WordsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/users/home_helper.rb
module Users::HomeHelper
end

app/helpers/users/results_helper.rb
module Users::ResultsHelper
end

app/helpers/users/users_helper.rb
module Users::UsersHelper
end

app/helpers/users/words_helper.rb
module Users::WordsHelper
end

app/views/admins/genres/_form.html.erb
<%= form_with model: [:admins, genre], local: true do |f| %>

  <%= render 'layouts/error_messages', obj: genre %>

  <%= f.label :name, "ジャンル名の入力" %>
  <%= f.text_field :name %>
  <%= f.radio_button :is_valid, "true" %>
  <%= f.label :is_valid, "有効" %>
  <%= f.radio_button :is_valid, "false" %>
  <%= f.label :is_valid, "無効" %>
  <%= f.submit submit, class:"btn btn-default" %>
<% end %>

app/views/admins/genres/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-5 col-xs-offset-2">
      <h2>ジャンル編集</h2>
      <%= render 'form', genre: @genre, submit: '更新' %>
    </div>
  </div>
</div>

app/views/admins/genres/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-5 col-xs-offset-2">
      <h2>ジャンル一覧 / 登録</h2>
      <%= render 'form', genre: @genre, submit: '登録' %>
    </div>
  </div>

  <div class="row">
    <div class="col-xs-4 col-xs-offset-2">
      <table class="table">
        <thead>
          <tr>
            <th>ジャンル名</th>
            <th>ステータス</th>
            <th></th>
          </tr>
        </thead>
        <tbody>
          <% @genres.each do |genre| %>
          <tr>
            <td><%= genre.name %></td>
            <% if genre.is_valid == true %>
            <td>有効</td>
            <% elsif genre.is_valid == false %>
            <td>無効</td>
            <% end %>
            <td><%= link_to '編集', edit_admins_genre_path(genre.id), class:"btn btn-primary" %></td>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>