config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, controllers: {
  sessions:      'admins/sessions',
  passwords:     'admins/passwords',
  # registrations: 'admins/registrations'
}

  devise_for :users, controllers: {
  sessions:      'users/sessions',
  passwords:     'users/passwords',
  registrations: 'users/registrations'
}

  scope module: :users do
    root 'home#top'
    get 'about' => 'home#about', as: :about
    get 'level' => 'questions#level', as: :level
    resources :users, only: [:show, :edit, :update]
    resources :words, only: [:index] do
      resource :favorites, only: [:create, :destroy]
    end
    resources :favorites, only: [:index]
    resources :questions, only: [:show, :create]
    post 'questions/:id' => 'questions#next', as: :next
    resources :results, only: [:index, :show]
  end

  get 'search' => 'search#search', as: :search

  namespace :admins do
    resources :admins, only: [:show, :edit, :update]
    resources :genres, only: [:index, :create, :edit, :update]
    resources :words, only: [:index, :new, :show, :create, :edit, :update]
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/choice.rb
class Choice < ApplicationRecord
  belongs_to :word
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :word
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :words

  validates :name, presence: true, length: {maximum: 50}
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :user
  belongs_to :word
end

app/models/result.rb
class Result < ApplicationRecord
  belongs_to :user
  has_many :result_details, dependent: :destroy
end

app/models/result_detail.rb
class ResultDetail < ApplicationRecord
  belongs_to :word
  belongs_to :result
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :authentication_keys => [:name]

  has_many :questions, dependent: :destroy
  has_many :results, dependent: :destroy
  has_many :favorites, dependent: :destroy

  # バリデーション
  validates :name, presence: true, uniqueness: true, length: {maximum: 50}

  #登録時にメールアドレスを不要とする
  def email_required?
    false
  end

  def email_changed?
    false
  end
end

app/models/word.rb
class Word < ApplicationRecord
	# refile指定のカラムにアクセス
	attachment :image

	belongs_to :genre

	has_many :favorites, dependent: :destroy
	has_many :questions, dependent: :destroy
	has_many :result_details, dependent: :destroy
	has_many :choices, dependent: :destroy

	accepts_nested_attributes_for :choices

	validates :english, presence: true, length: {maximum: 50}
	validates :japanese, presence: true, length: {maximum: 50}

	def favorite_by?(user)
		favorites.where(user_id: user.id).exists?
	end
end

app/controllers/admins/words_controller.rb
class Admins::WordsController < ApplicationController
  before_action :authenticate_admin!

  def index
    @words = Word.all
  end

  def new
    @word = Word.new
    @genres = Genre.where(is_valid: true)
    4.times {
      @word.choices.build
    }
  end

  def show
    @word = Word.find(params[:id])
    @choices = @word.choices.all
  end

  def create
    @word = Word.new(word_params)
    @word.genre_id = params[:word][:genre_id]
    if @word.save
      redirect_to admins_words_path
    else
      @genres = Genre.where(is_valid: true)
      render :new
    end
  end

  def edit
    @word = Word.find(params[:id])
    @genres = Genre.where(is_valid: true)
  end

  def update
    word = Word.find(params[:id])
    word.genre_id = params[:word][:genre_id]
    if word.update(word_params)
      redirect_to admins_words_path
    else
      @genres = Genre.where(is_valid: true)
      render :edit
    end
  end

  private

    def word_params
      params.require(:word).permit(:english, :japanese, :image, :is_valid,
                                    choices_attributes: [:id, :content])
    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  protected

  def after_sign_in_path_for(resource_or_scope)
    if resource_or_scope.is_a?(Admin)
      admins_admin_path(current_admin)
    else
      level_path
    end
  end

  #sign_out後のredirect先変更する。
  def after_sign_out_path_for(resource_or_scope)
    if resource_or_scope == :user
      root_path
    elsif resource_or_scope == :admin
      new_admin_session_path
    else
      root_path
    end
  end

  Refile.secret_key = '9965eb0ced03aae4584924c8af339f5521d5bd5a8e7e68f158b12b57ea6a0dc8f2cd99f49dd9f4140b4005b4345e57f1da38d037b9c045d40ef3b61179d8418b'
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  def search
    @text = params[:search][:text]
    @words = Word.where(['english LIKE ? OR japanese LIKE ?', '%'+@text+'%', '%'+@text+'%'])
  end
end

app/controllers/users/words_controller.rb
class Users::WordsController < ApplicationController
  before_action :authenticate_user!

  def index
    @words = Word.all
  end
end

app/helpers/admins/admins_helper.rb
module Admins::AdminsHelper
end

app/helpers/admins/genres_helper.rb
module Admins::GenresHelper
end

app/helpers/admins/home_helper.rb
module Admins::HomeHelper
end

app/helpers/admins/words_helper.rb
module Admins::WordsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/users/favorites_helper.rb
module Users::FavoritesHelper
end

app/helpers/users/home_helper.rb
module Users::HomeHelper
end

app/helpers/users/results_helper.rb
module Users::ResultsHelper
end

app/helpers/users/users_helper.rb
module Users::UsersHelper
end

app/helpers/users/words_helper.rb
module Users::WordsHelper
end

app/views/admins/words/_form.html.erb
<%= form_with model: [:admins, word], local: true do |f| %>

  <%= render 'layouts/error_messages', obj: word %>

  <div class="form-group">
    <%= f.attachment_field :image %>
  </div>
  <div class="form-group">
    <p><%= f.label :english, "英単語の入力" %></p>
    <%= f.text_field :english %>
  </div>
  <div class="form-group">
    <p><%= f.label :japanese, "日本語の入力" %></p>
    <%= f.text_field :japanese %>
  </div>
  <div class="form-group">
    <p><%= f.label :genre_name, "ジャンル選択" %></p>
    <%= f.select :genre_id, genres.map { |genre| [genre.name, genre.id] }, { include_blank: '選択してください'} %>
  </div>
  <p>
    問題で出題する単語の選択肢を入力してください。</br>
    <注>正解となる単語も、もう一度入力してください。
  </p>
  <% i = 1 %>
  <%= f.fields_for :choices do |choice_field| %>
    <div class="form-group">
      <%= choice_field.label :content, "選択肢#{i}：" %>
      <%= choice_field.text_field :content %>
      <% i = i + 1 %>
    </div>
  <% end %>
  <%= f.submit submit, class:"btn btn-default" %>
<% end %>

app/views/admins/words/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-5 col-xs-offset-2">
      <h2>単語編集</h2>
      <%= render 'form', word: @word, genres: @genres, submit: '更新' %>
    </div>
  </div>
</div>

app/views/admins/words/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-8 col-xs-offset-2">
      <h2>単語一覧</h2>
      <%= link_to '単語新規登録', new_admins_word_path, class:"btn btn-primary" %>
      <%= link_to 'ジャンル一覧 / 登録', admins_genres_path, class:"btn btn-warning" %>
      <table class="table admins-words__table">
        <thead>
          <tr class="admins-words__table-head">
            <th>画像</th>
            <th>単語</th>
            <th>日本語訳</th>
            <th>ジャンル</th>
            <th>ステータス</th>
            <th></th>
          </tr>
        </thead>
        <tbody>
          <% @words.each do |word| %>
          <tr>
            <td><%= attachment_image_tag word, :image, format: 'jpeg', size: "40x30" %></td>
            <td><%= link_to word.english, admins_word_path(word.id) %></td>
            <td><%= word.japanese %></td>
            <td><%= word.genre.name %></td>
            <td>
              <% if word.is_valid == true %>
              有効
              <% else %>
              無効
              <% end %>
            </td>
            <td><%= link_to '編集', edit_admins_word_path(word.id), class:"btn btn-success" %></td>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/admins/words/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-5 col-xs-offset-2">
      <h2>単語登録</h2>
      <%= render 'form', word: @word, genres: @genres, submit: '登録' %>
    </div>
  </div>
</div>

app/views/admins/words/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-5">
      <h2>単語詳細</h2>
      <div>
        <%= attachment_image_tag @word, :image, format: 'jpeg', size: "100x100" %>
      </div>
      <p>英単語</p>
      <p><%= @word.english %></p>

      <p>日本語</p>
      <p><%= @word.japanese %></p>

      <p>選択肢</p>
      <% @choices.each do |choice| %>
        <p><%= choice.content %></p>
      <% end %>
    </div>
  </div>
</div>