config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, controllers: {
  sessions:      'admins/sessions',
  passwords:     'admins/passwords',
  # registrations: 'admins/registrations'
}

  devise_for :users, controllers: {
  sessions:      'users/sessions',
  passwords:     'users/passwords',
  registrations: 'users/registrations'
}

  scope module: :users do
    root 'home#top'
    get 'about' => 'home#about', as: :about
    get 'level' => 'questions#level', as: :level
    resources :users, only: [:show, :edit, :update]
    resources :words, only: [:index] do
      resource :favorites, only: [:create, :destroy]
    end
    resources :favorites, only: [:index]
    resources :questions, only: [:show, :create]
    post 'questions/:id' => 'questions#next', as: :next
    resources :results, only: [:index, :show]
  end

  get 'search' => 'search#search', as: :search

  namespace :admins do
    resources :admins, only: [:show, :edit, :update]
    resources :genres, only: [:index, :create, :edit, :update]
    resources :words, only: [:index, :new, :show, :create, :edit, :update]
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/choice.rb
class Choice < ApplicationRecord
  belongs_to :word
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :word
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :words

  validates :name, presence: true, length: {maximum: 50}
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :user
  belongs_to :word
end

app/models/result.rb
class Result < ApplicationRecord
  belongs_to :user
  has_many :result_details, dependent: :destroy
end

app/models/result_detail.rb
class ResultDetail < ApplicationRecord
  belongs_to :word
  belongs_to :result
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :authentication_keys => [:name]

  has_many :questions, dependent: :destroy
  has_many :results, dependent: :destroy
  has_many :favorites, dependent: :destroy

  # バリデーション
  validates :name, presence: true, uniqueness: true, length: {maximum: 50}

  #登録時にメールアドレスを不要とする
  def email_required?
    false
  end

  def email_changed?
    false
  end
end

app/models/word.rb
class Word < ApplicationRecord
	# refile指定のカラムにアクセス
	attachment :image

	belongs_to :genre

	has_many :favorites, dependent: :destroy
	has_many :questions, dependent: :destroy
	has_many :result_details, dependent: :destroy
	has_many :choices, dependent: :destroy

	accepts_nested_attributes_for :choices

	validates :english, presence: true, length: {maximum: 50}
	validates :japanese, presence: true, length: {maximum: 50}

	def favorite_by?(user)
		favorites.where(user_id: user.id).exists?
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  protected

  def after_sign_in_path_for(resource_or_scope)
    if resource_or_scope.is_a?(Admin)
      admins_admin_path(current_admin)
    else
      level_path
    end
  end

  #sign_out後のredirect先変更する。
  def after_sign_out_path_for(resource_or_scope)
    if resource_or_scope == :user
      root_path
    elsif resource_or_scope == :admin
      new_admin_session_path
    else
      root_path
    end
  end

  Refile.secret_key = '9965eb0ced03aae4584924c8af339f5521d5bd5a8e7e68f158b12b57ea6a0dc8f2cd99f49dd9f4140b4005b4345e57f1da38d037b9c045d40ef3b61179d8418b'
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  def search
    @text = params[:search][:text]
    @words = Word.where(['english LIKE ? OR japanese LIKE ?', '%'+@text+'%', '%'+@text+'%'])
  end
end

app/helpers/admins/admins_helper.rb
module Admins::AdminsHelper
end

app/helpers/admins/home_helper.rb
module Admins::HomeHelper
end

app/helpers/admins/words_helper.rb
module Admins::WordsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/users/home_helper.rb
module Users::HomeHelper
end

app/helpers/users/users_helper.rb
module Users::UsersHelper
end

app/helpers/users/words_helper.rb
module Users::WordsHelper
end

app/views/admins/admins/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-5">
      <%= form_with model: current_admin, url: admins_admin_path(current_admin), method: :patch, local: true do |f| %>
      <%= f.label :email, "メールアドレス" %>
      <%= f.email_field :email %>
      <%= f.submit "更新" %>
      <% end %>
    </div>
  </div>
</div>

app/views/admins/admins/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-3">
      <h2>マイページ</h2>
      <table class="table table-bordered">
        <tr>
          <th>メールアドレス</th>
          <td><%= current_admin.email %></td>
        </tr>
      </table>
      <div class="row">
        <div class="col-xs-3">
          <%= link_to '編集', edit_admins_admin_path(current_admin), class:"btn btn-primary" %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/admins/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admins/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "こちら", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "こちら", new_registration_path(resource_name) %><br />
<% end %>

<%#- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%#= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<%# end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end %>
<% end %>